export const REQUEST_CREATE_REQUEST = "REQUEST_CREATE_REQUEST";
export const REQUEST_CREATE_SUCCESS = "REQUEST_CREATE_SUCCESS";
export const REQUEST_CREATE_FAIL = "REQUEST_CREATE_FAIL";

export const IS_BOOKED_CREATE_REQUEST = "IS_BOOKED_CREATE_REQUEST";
export const IS_BOOKED_CREATE_SUCCESS = "IS_BOOKED_CREATE_SUCCESS";
export const IS_BOOKED_CREATE_FAIL = "IS_BOOKED_CREATE_FAIL";

export const CAN_CANCEL_CREATE_REQUEST = "CAN_CANCEL_CREATE_REQUEST";
export const CAN_CANCEL_CREATE_SUCCESS = "CAN_CANCEL_CREATE_SUCCESS";
export const CAN_CANCEL_CREATE_FAIL = "CAN_CANCEL_CREATE_FAIL";

export const CANCEL_CREATE_REQUEST = "CANCEL_CREATE_REQUEST";
export const CANCEL_CREATE_SUCCESS = "CANCEL_CREATE_SUCCESS";
export const CANCEL_CREATE_FAIL = "CANCEL_CREATE_FAIL";

export const ALL_REQUEST_CREATE_REQUEST = "ALL_REQUEST_CREATE_REQUEST";
export const ALL_REQUEST_CREATE_SUCCESS = "ALL_REQUEST_CREATE_SUCCESS";
export const ALL_REQUEST_CREATE_FAIL = "ALL_REQUEST_CREATE_FAIL";

export const USER_REQUEST_CREATE_REQUEST = "USER_REQUEST_CREATE_REQUEST";
export const USER_REQUEST_CREATE_SUCCESS = "USER_REQUEST_CREATE_SUCCESS";
export const USER_REQUEST_CREATE_FAIL = "USER_REQUEST_CREATE_FAIL";

export const INDIVIDUAL_REQUEST_CREATE_REQUEST = "INDIVIDUAL_REQUEST_CREATE_REQUEST";
export const INDIVIDUAL_REQUEST_CREATE_SUCCESS = "INDIVIDUAL_REQUEST_CREATE_SUCCESS";
export const INDIVIDUAL_REQUEST_CREATE_FAIL = "INDIVIDUAL_REQUEST_CREATE_FAIL";
