const Books = [
    {
        _id: "1",
        name: "Millionaire Mindset",
        image: "/images/Millionaire Mindset.webp",
        description:
            "Have you heard this saying: You have to think rich to be rich? This is another way of saying that the wealthy people all think as one. This is especially so when it comes to the way they manage their finances. Learn how to think like the rich do. A huge number of millionaires earned their millions by working for it. Only a little fraction of the rich inherited it. What does this show? It shows that the majority of the wealthy people had to work it through, following consistently with their vision to succeed.You can actually live out your dreams. Knowing that there is a mindset that millionaires live by is another way of saying that that can live that way and also become a millionaire in time. After all, a millionaire is a normal person who has stuck with the principles of financial success. If you can stick with it, you can make it right to the very top.",
        author: "Paul J. Stanley",
        genre: "Business",
        ageCategory: "old aged",
        publishedDate: "04/17/2018",
        noOfPages: 250,
        publicationName: "Author's Republic",
        editionNumber: 2,
        finePerWeek: 25,
        noOfReviews: 6,
        ratings: 4,
        floorNumber: 1,
        rackNumber: 10,
        rowNumber: 3,
        positionFromLeft: 2,
    },
    {
        _id: "2",
        name: "The Da Vinci Code",
        image: "/images/The Da Vinci Code.jpg",
        description:
            "The record-breaking bestseller A man is murdered in the worlds most famous museum. Around his body is a ring of codes, drawn in blood. He died to protect a secret which Robert Langdon must uncover. It will be a race against time to decipher this final message. Can he get there before the killers do?",
        author: "Dan Brown",
        genre: "Thriller",
        ageCategory: "middle aged",
        publishedDate: "08/28/2009",
        noOfPages: 592,
        publicationName: "RHUK",
        editionNumber: 52,
        finePerWeek: 35,
        noOfReviews: 11,
        ratings: 4.5,
        floorNumber: 2,
        rackNumber: 23,
        rowNumber: 5,
        positionFromLeft: 7,
    },
    {
        _id: "3",
        name: "Harry Potter and the Deathly Hallows",
        image: "/images/Harry Potter and the Deathly Hallows.jpg",
        description:
            "Harry has been burdened with a dark, dangerous and seemingly impossible task: that of locating and destroying Voldemort's remaining Horcruxes. Never has Harry felt so alone, or faced a future so full of shadows. But Harry must somehow find within himself the strength to complete the task he has been given. He must leave the warmth, safety and companionship of The Burrow and follow without fear or hesitation the inexorable path laid out for him...",
        author: "J K Rowling",
        genre: "Fantasy",
        ageCategory: "teen",
        publishedDate: "01/23/2005",
        noOfPages: 607,
        publicationName: "Bloomsbury",
        editionNumber: 1,
        finePerWeek: 15,
        noOfReviews: 18,
        ratings: 3.5,
        floorNumber: 3,
        rackNumber: 7,
        rowNumber: 1,
        positionFromLeft: 1,
    },
    {
        _id: "4",
        name: "Fifty Shades of Grey",
        image: "/images/Fifty Shades of Grey.jpg",
        description:
            "Fifty Shades of Grey of by E. L. James is a romantic thriller that comes with a supernatural twist. An erotic romantic novel, it is the first part in the Fifty Shades Trilogy that tracks the relationship between a college girl and a young successful business person. Based around Anastasia Steele, a 21-year old college girl who on behalf of her friend Kate interviews Christian Grey, an uber rich successful businessman. The unfolding sadomasochistic relationship turns ugly as the plot, filled with many twists and turns, further reveals about how the life of a simple college girl, who fell in love with the rich person, turns her world upside down. The book that is known for its daring, bold and erotic descriptions, actually depicts about human bondage, dominance, sadism and submission. Popularity of the book has also been adapted into a famous Hollywood film that goes by the same name and does feature many bold romantic scenes. ",
        author: "E L James",
        genre: "Romance",
        ageCategory: "middle aged",
        publishedDate: "04/12/2012",
        noOfPages: 560,
        publicationName: "RHUK",
        editionNumber: 1,
        finePerWeek: 10,
        noOfReviews: 8,
        ratings: 3,
        floorNumber: 2,
        rackNumber: 7,
        rowNumber: 2,
        positionFromLeft: 8,
    },
    {
        _id: "5",
        name: "The Lost Symbol",
        image: "/images/The Lost Symbol.webp",
        description:
            "NOW A MAJOR TELEVISION SERIES The Capitol Building, Washington DC: Harvard symbologist Robert Langdon believes he is here to give a lecture. He is wrong. Within minutes of his arrival, a shocking object is discovered. It is a gruesome invitation into an ancient world of hidden wisdom.When Langdon's mentor, Peter Solomon - prominent mason and philanthropist - is kidnapped, Langdon realizes that his only hope of saving his friend's life is to accept this mysterious summons.It is to take him on a breathless chase through Washington's dark history. All that was familiar is changed into a shadowy, mythical world in which Masonic secrets and never-before-seen revelations seem to be leading him to a single impossible and inconceivable truth...",
        author: "Dan Brown",
        genre: "Thriller",
        ageCategory: "all",
        publishedDate: "07/22/2010",
        noOfPages: 670,
        publicationName: "Corgi",
        editionNumber: 5,
        finePerWeek: 5,
        noOfReviews: 2,
        ratings: 2,
        floorNumber: 3,
        rackNumber: 1,
        rowNumber: 1,
        positionFromLeft: 5,
    },
    {
        _id: "6",
        name: "New Moon",
        image: "/images/New Moon.jpg",
        description:
            "I stuck my finger under the edge of the paper and jerked it under the tape. 'Shoot,' I muttered when the paper sliced my finger. A single drop of blood oozed from the tiny cut. It all happened very quickly then. 'No!' Edward roared ... Dazed and disorientated, I looked up from the bright red blood pulsing out of my arm - and into the fevered eyes of the six suddenly ravenous vampires.",
        author: "Stephenie Meyer",
        genre: "Romance",
        ageCategory: "kids",
        publishedDate: "04/05/2007",
        noOfPages: 576,
        publicationName: "Little, Brown Book Group",
        editionNumber: 5,
        finePerWeek: 30,
        noOfReviews: 9,
        ratings: 4,
        floorNumber: 2,
        rackNumber: 5,
        rowNumber: 1,
        positionFromLeft: 7,
    },
];

export default Books;
